apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-visualiser-app
  labels:
    app: stats-visualiser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-visualiser
  template:
    metadata:
      labels:
        app: stats-visualiser
    spec:
      initContainers:
        - name: copy-app-files
          image: stats-visualiser-app:latest
          imagePullPolicy: Never
          command: ['/bin/sh', '-c', 'cp -r /var/www/html/. /app/']
          volumeMounts:
            - name: app-code
              mountPath: /app
      containers:
        - name: nginx
          image: nginx:stable
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
        - name: stats-visualiser-app
          image: stats-visualiser-app:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: sqlite-storage
              mountPath: /var/www/html/var

      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: app-storage-sqlite-pvc
        - name: app-code
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
